### ISSUE TITLE
PA Review: Comments

### ISSUE THREAD

**Issue by candyapplecorn** [candyapplecorn/discourse#19]
Users should be able to create, read and delete comments.

**Comment by candyapplecorn** [comment]
Users can view comments whether they're logged in or not. If they're logged in, users can see a comment form which allows updating and creating comments. Comments have buttons for updating and deleting themselves, which only comments' authors may see/use. Otherwise, instead of those edit and delete buttons, the comment's author's username is displayed. Additionally, comment counts appear on storyIndexItems (the stories on the splash page)

**Comment by rkoeze** [comment]
When we edit a comment can we do that in the index item and not have to navigate back to the comment form at the top of the comments section?

**Comment by rkoeze** [comment]
Otherwise looks great!

**Comment by candyapplecorn** [comment]
Ok, I will work on that.

**Comment by candyapplecorn** [comment]
Editing/Updating comments is now done in-line

**Comment by rkoeze** [comment]
Looks fantastic. Let's seed a couple more comments and then we're done. Great job!

**Comment by candyapplecorn** [comment]
Should be ready to go now
