### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by candyapplecorn** [candyapplecorn/discourse#2]
Users should be able to register and sign in / out. There should be a user show page which should include a portrait of the user, their username and a short bio.

Additionally, the header and footer for the website should exist.

https://write-it-up.herokuapp.com

**Comment by candyapplecorn** [comment]
https://write-it-up.herokuapp.com

@rkoeze

**Comment by rkoeze** [comment]
Auth looks good. Two things: 

1) It looks like the element for the middle auth button is styled differently from the other auth buttons on your modal. Let's make them consistent. 

2) On the navbar, you have the text `Sign up/Login`. Split these two elements up so it's clear clicking them pushes you to a different route. Don't use the `/`.

Fix these things and we're good to go. Great job!

**Comment by candyapplecorn** [comment]
Ok, I addressed those things. I also have unstyled new, edit and show for stories
